fname = input("Enter your first name: ")
lname = input("Enter your last name: ")
mname = input("Enter your middle name: ")
bday = input("Enter your birthday (MM/DD/YYYY): ")
gender = input("Enter gender (M/F): ")
add = input("Enter current address: ")
course = input("Enter course: ")
year = input("Enter year level: ")
print("First Name: "+fname)
print("Last Name: "+lname)
print("Middle Name: "+mname)
print("Birthday: "+bday)
print("Gender: "+gender)
print("Current Address: "+add)
print("Course: "+course)
print("Year Level: "+year)